
// Exception 

public void Example1() throws Exception {
  // exception try-catch
  try {
    int[] myNumbers = {1, 2, 3};
    System.out.println(myNumbers[10]);
  } catch (Exception e) {
    System.out.println("Something went wrong.");
  }
}

public void Example2() throws IOException, SecurityException {
  // exception try-catch-finally 
  try {
    int[] myNumbers = {1, 2, 3};
    System.out.println(myNumbers[10]);
  } catch (Exception e) {
    System.out.println("Something went wrong.");
  } finally {
    System.out.println("The 'try catch' is finished.");
  }
}

// throw statement

public void Example3() throws IOException, Exception, FileNotFoundException, NullPointerException, MyException {
  // exception throw 
  try {
    int[] myNumbers = {1, 2, 3};
    System.out.println(myNumbers[10]);
  } catch (Exception e) {
    System.out.println(e.printStackTrace());
    System.out.println(e.getMessage());
  
    throw new NullPointerException("нулпоинтер");
    // throw new MyException();
  }
}


//
